### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by M4rt1n12** [netwrix/pingcastle#266]
```
[17:31:24] An exception occurred when doing the task: application domain
Note: you can run the program with the switch --log to get more detail
Exception: The file or assembly "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of its dependencies could not be found. The system cannot find the file specified.
file:System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
at PingCastle.Cloud.Common.HttpClientHelper.EnableLoging(SazGenerator generator)
at PingCastle.Program.Main(String[] args)

Unhandled exception: System.IO.FileNotFoundException: The file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies could not be found. The system cannot find the file specified.
at PingCastle.Cloud.Common.HttpClientHelper.EnableLoging(SazGenerator generator)
 at PingCastle.Program.Main(String[] args)
PS C:\Users\Administrator\Downloads\PingCastle_3.3.0.1>
```

Windows Server 2016 Version 1607 (Build 14393.7428)

Installed Software:
```
DisplayName                                                    DisplayVersion Publisher                       InstallDate
-----------                                                    -------------- ---------                       -----------
AD LDS-Instanz "AGATHON"                                                      Microsoft Corporation                      
Mozilla Firefox (x64 de)                                       132.0.2        Mozilla                                    
Mozilla Maintenance Service                                    59.0.2         Mozilla                                    
Product Library                                                6.0.1308       KYOCERA Document Solutions Inc.            
TeamViewer Host                                                15.59.3        TeamViewer                                 
Microsoft .NET Host FX Resolver - 8.0.10 (x64)                 64.40.21578    Microsoft Corporation           20241112   
Microsoft .NET Runtime - 8.0.10 (x64)                          64.40.21578    Microsoft Corporation           20241112   
Microsoft .NET Host - 8.0.10 (x64)                             64.40.21578    Microsoft Corporation           20241112   
Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.40.33816    14.40.33816    Microsoft Corporation           20241112   
Microsoft Visual C++ 2022 X64 Additional Runtime - 14.40.33816 14.40.33816    Microsoft Corporation           20241112   
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161 9.0.30729.6161 Microsoft Corporation           20180405   
Microsoft Windows Desktop Runtime - 8.0.10 (x64)               64.40.21605    Microsoft Corporation           20241112   
VMware Tools                                                   10.2.5.8068406 VMware, Inc.                    20201207   
PowerShell 7-x64                                               7.4.6.0        Microsoft Corporation           20241112   
NSClient++ (x64)                                               0.5.2039       MySolutions NORDIC              20180409   
Zabbix Agent 2 (64-bit)                                        6.4.8.2400     Zabbix SIA                      20231113
```

**Comment by JoeDibley** [comment]
Hi there,
Just need to install .NET 4.7.2. 
Link: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472
